name: End-to-end tests
on: push
env:
  API_BASE_URL: 'https://qna-fwmh.onrender.com'
  FRONTEND_URL: 'http://localhost:3000'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: node ./.output/server/index.mjs
          wait-on: 'http://localhost:3000'
          working-directory: frontend
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
