name: End-to-end tests
on: push
env:
  API_BASE_URL: 'https://qna-fwmh.onrender.com'
  FRONTEND_URL: 'https://try-qna.vercel.app'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
